apiVersion: apps/v1
kind: Deployment
metadata:
  name: wstunnel-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wstunnel
  template:
    metadata:
      labels:
        app: wstunnel
    spec:
      containers:
        - name: wstunnel
          image: wstunnel:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_INTERNAL_PORT
              value: "8081"
            - name: SECRET_CERT
              valueFrom:
                secretKeyRef:
                  name: wstunnel-cert
                  key: tls.crt
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wstunnel-cert
                  key: tls.key
            - name: JWT_CERT
              valueFrom:
                secretKeyRef:
                  name: wstunnel-cert
                  key: tls.crt
---
apiVersion: v1
kind: Service
metadata:
  name: wstunnel-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: wstunnel
